name: Prebuild and Publish Dev Container

on:
  push:
    branches:
      - main
    paths:
      - .devcontainer/**
      - .github/workflows/prebuild.yaml

env:
  PASSWORD: ${{ secrets.PREBUILD_PASSWORD || secrets.GITHUB_TOKEN }}
  PLATFORMS: ${{ vars.PREBUILD_PLATFORMS || 'linux/amd64,linux/arm64' }}
  PUSH: ${{ vars.PREBUILD_PUSH || 'filter' }}
  REGISTRY: ${{ vars.PREBUILD_REGISTRY || 'ghcr.io' }}
  REPOSITORY: ${{ vars.PREBUILD_REPOSITORY || github.repository }}
  USERNAME: ${{ vars.PREBUILD_USERNAME || github.actor }}

jobs:
  prebuild:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Prebuild Environment
        id: setup
        uses: cennis91/setup-prebuild-env@v1
        with:
          password: ${{ env.PASSWORD }}
          platforms: ${{ env.PLATFORMS }}
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}

      - name: Prebuild and Publish Image
        uses: devcontainers/ci@v0.3
        env:
          PUSH: ${{ env.PUSH }}
          REGISTRY: ${{ env.REGISTRY }}
          REPOSITORY: ${{ env.REPOSITORY }}
        with:
          imageName: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/devcontainer
          imageTag: latest
          push: ${{ env.PUSH }}
          refFilterForPush: |
            refs/heads/main
          eventFilterForPush: push
          platform: ${{ steps.setup.outputs.platforms }}
